### ISSUE TITLE
Does /web need to even exist within the repo?

### ISSUE THREAD

**Issue by benhosmer** [radiantbluetechnologies/tuple#9]
Since we're actually building tuple and then /web hosts the document root etc., does the /web directory need to be captured here?

**Comment by mpgerlek** [comment]
tuple/rialto-viewer/web? No, it doesn’t need to persist - we should build the app, then copy the build dir off to wherever the static-file-server-root is.

-mpg



On Mar 23, 2015, at 7:39 AM, Ben Hosmer <notifications@github.com<mailto:notifications@github.com>> wrote:


Since we're actually building tuple and then /web hosts the document root etc., does the /web directory need to be captured here?

**Comment by benhosmer** [comment]
Cool, I'll get some pull requests in today. Right now I have a build container that builds and then outputs the /web with the finished product. The viewer container just uses the /web as a shared volume and launches nginx to view.
